name: CloudHub Deployment with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cloudhubdeployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out code Repo 
      uses: actions/checkout@v3
        
    - name: Build and deploy with Maven
      run: mvn clean deploy -DmuleDeploy -B package --file pom.xml -s .maven/settings.xml
