name: CloudHub Deployment with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cloudhubdeployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out code Repo 
      uses: actions/checkout@v3
      env:
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}        
    - name: Build and deploy with Maven
      run: mvn clean deploy -DmuleDeploy -Denv.PLATFORM_USERNAME=maamar2023 -Denv.PLATFORM_PASSWORD=maa@Mar2023 -B package --file pom.xml -s .maven/settings.xml
